This notebook was copied with edits from VADIM KAMAEV's notebook :
https://www.kaggle.com/code/vadimkamaev/catboost-new/notebook

In [1]:
import pandas as pd, numpy as np
from catboost import CatBoostClassifier
import lightgbm as lgb
import pickle
import sys

# Load Train Data and Labels

In [2]:
dtypes = {"session_id": 'int64',
          "index": np.int16,
          "elapsed_time": np.int32,
          "event_name": 'category',
          "name": 'category',
          "level": np.int8,
          "page": np.float16,
          "room_coor_x": np.float16,
          "room_coor_y": np.float16,
          "screen_coor_x": np.float16,
          "screen_coor_y": np.float16,
          "hover_duration": np.float32,
          "text": 'category',
          "fqid": 'category',
          "room_fqid": 'category',
          "text_fqid": 'category',
          "fullscreen": np.int8,
          "hq": np.int8,
          "music": np.int8,
          "level_group": 'category'
          }
use_col = ['session_id', 'index', 'elapsed_time', 'event_name', 'name', 'level', 'page',
           'room_coor_x', 'room_coor_y', 'hover_duration', 'text', 'fqid', 'room_fqid', 'text_fqid', 'level_group']

In [3]:
targets = pd.read_csv('/kaggle/input/predict-student-performance-from-game-play/train_labels.csv')
targets['session'] = targets.session_id.apply(lambda x: int(x.split('_')[0]) )
targets['q'] = targets.session_id.apply(lambda x: int(x.split('_')[-1][1:]) )
print( targets.shape )
targets.head()

(424116, 4)

             session_id  correct            session  q
0  20090312431273200_q1        1  20090312431273200  1
1  20090312433251036_q1        0  20090312433251036  1
2  20090312455206810_q1        1  20090312455206810  1
3  20090313091715820_q1        0  20090313091715820  1
4  20090313571836404_q1        1  20090313571836404  1

In [4]:
feature_df = pd.read_csv('/kaggle/input/featur/feature_sort.csv')

# Feature Engineer

In [5]:
def delt_time_def(df):
    df.sort_values(by=['session_id', 'elapsed_time'], inplace=True)
    df['d_time'] = df['elapsed_time'].diff(1)
    df['d_time'].fillna(0, inplace=True)
    df['delt_time'] = df['d_time'].clip(0, 103000)
    df['delt_time_next'] = df['delt_time'].shift(-1)
    return df

In [6]:
def feature_engineer(train, kol_f):
    global kol_col, kol_col_max
    kol_col = 9
    kol_col_max = 11+kol_f*2
    col = [i for i in range(0,kol_col_max)]
    new_train = pd.DataFrame(index=train['session_id'].unique(), columns=col, dtype=np.float16)  
    new_train[10] = new_train.index # "session_id"    

    new_train[0] = train.groupby(['session_id'])['d_time'].quantile(q=0.3)
    new_train[1] = train.groupby(['session_id'])['d_time'].quantile(q=0.8)
    new_train[2] = train.groupby(['session_id'])['d_time'].quantile(q=0.5)
    new_train[3] = train.groupby(['session_id'])['d_time'].quantile(q=0.65)
    new_train[4] = train.groupby(['session_id'])['hover_duration'].agg('mean')
    new_train[5] = train.groupby(['session_id'])['hover_duration'].agg('std')    
    new_train[6] = new_train[10].apply(lambda x: int(str(x)[:2])).astype(np.uint8) # "year"
    new_train[7] = new_train[10].apply(lambda x: int(str(x)[2:4])+1).astype(np.uint8) # "month"
    new_train[8] = new_train[10].apply(lambda x: int(str(x)[4:6])).astype(np.uint8) # "day"
    new_train[9] = new_train[10].apply(lambda x: int(str(x)[6:8])).astype(np.uint8) + new_train[10].apply(lambda x: int(str(x)[8:10])).astype(np.uint8)/60
    new_train[10] = 0
    new_train = new_train.fillna(-1)
    
    return new_train

In [7]:
def feature_next_t(row_f, new_train, train, gran_1, gran_2, i):
    global kol_col
    kol_col +=1
    col1 = row_f['col1']
    val1 = row_f['val1']
    maska = (train[col1] == val1)
    if row_f['kol_col'] == 1:       
        new_train[kol_col] = train[maska].groupby(['session_id'])['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska].groupby(['session_id'])['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska].groupby(['session_id'])['index'].count()          
    elif row_f['kol_col'] == 2: 
        col2 = row_f['col2']
        val2 = row_f['val2']
        maska = maska & (train[col2] == val2)        
        new_train[kol_col] = train[maska].groupby(['session_id'])['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska].groupby(['session_id'])['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska].groupby(['session_id'])['index'].count()
    return new_train

In [8]:
def feature_next_t_otvet(row_f, new_train, train, gran_1, gran_2, i):
    global kol_col
    kol_col +=1
    col1 = row_f['col1']
    val1 = row_f['val1']
    maska = (train[col1] == val1)
    if row_f['kol_col'] == 1:      
        new_train[kol_col] = train[maska]['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska]['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska]['index'].count()          
    elif row_f['kol_col'] == 2: 
        col2 = row_f['col2']
        val2 = row_f['val2']
        maska = maska & (train[col2] == val2)        
        new_train[kol_col] = train[maska]['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska]['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska]['index'].count()
    return new_train

In [9]:
def experiment_feature_next_t_otvet(row_f, new_train, train, gran_1, gran_2, i):
    global kol_col
    kol_col +=1
    if row_f['kol_col'] == 1: 
        maska = train[row_f['col1']] == row_f['val1']
        new_train[kol_col] = train[maska]['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska]['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska]['index'].count()          
    elif row_f['kol_col'] == 2: 
        col2 = row_f['col2']
        val2 = row_f['val2']
        maska = (train[col1] == val1) & (train[col2] == val2)        
        new_train[kol_col] = train[maska]['delt_time_next'].sum()
        if gran_1:
            kol_col +=1
            new_train[kol_col] = train[maska]['delt_time'].mean()
        if gran_2:
            kol_col +=1
            new_train[kol_col] = train[maska]['index'].count()
    return new_train

In [10]:
def feature_quest_otvet(new_train, train, quest, kol_f):
    global kol_col
    kol_col = 9
    g1 = 0.7 
    g2 = 0.3 

    feature_q = feature_df[feature_df['quest'] == quest].copy()
    feature_q.reset_index(drop=True, inplace=True)
    
    gran1 = round(kol_f * g1)
    gran2 = round(kol_f * g2)    
    for i in range(0, kol_f):         
        row_f = feature_q.loc[i]
        new_train = feature_next_t_otvet(row_f, new_train, train, i < gran1, i <  gran2, i) 
    col = [i for i in range(0,kol_col+1)]
    return new_train[col]

In [11]:
def feature_engineer_new(new_train, train, feature_q, kol_f):
    g1 = 0.7 
    g2 = 0.3 
    gran1 = round(kol_f * g1)
    gran2 = round(kol_f * g2)    
    for i in range(0, kol_f): 
        row_f = feature_q.loc[i]       
        new_train = feature_next_t(row_f, new_train, train, i < gran1, i <  gran2, i)         
    return new_train

In [12]:
def feature_quest(new_train, train, quest, kol_f):
    global kol_col
    kol_col = 9
    feature_q = feature_df[feature_df['quest'] == quest].copy()
    feature_q.reset_index(drop=True, inplace=True)
    new_train = feature_engineer_new(new_train, train, feature_q, kol_f)
    col = [i for i in range(0,kol_col+1)]
    return new_train[col]

In [13]:
from sklearn.linear_model import LogisticRegression
from xgboost import XGBClassifier

from sklearn.neural_network import MLPClassifier

def create_model(old_train, quests, models, list_kol_f):

    kol_quest = len(quests)
    
    # Iterate through questions
    for q in quests:
        print('### quest ', q, end='')
        new_train = feature_engineer(old_train, list_kol_f[q])
        train_x = feature_quest(new_train, old_train, q, list_kol_f[q])
        print(' ---- ', 'train_q.shape = ', train_x.shape)

        # TRAIN DATA
        train_users = train_x.index.values
        train_y = targets.loc[targets.q == q].set_index('session').loc[train_users]
    
     
        # XGBoost model
        xgb_model = XGBClassifier(
            learning_rate=0.25,
            max_depth=6,
            n_estimators= 300,
            gamma = 0.01, 
            alpha = 0.05,  
        )
        xgb_model.fit(train_x.astype('float32'), train_y['correct'])
        models[f'{q}_xgboost'] = xgb_model
        
        # CatBoost model
        cat_model = CatBoostClassifier(
            n_estimators = 300,
            learning_rate= 0.045,
            depth = 6
        )
        cat_model.fit(train_x.astype('float32'), train_y['correct'], verbose=False)
        models[f'{q}_catboost'] = cat_model
        
        # MLP model
        mlp_model = MLPClassifier(
            solver = 'sgd', 
            activation = 'logistic',
            max_iter = 300, 
            hidden_layer_sizes = (60,30,10),
            random_state = 1)
        mlp_model.fit(train_x.astype('float32').fillna(0), train_y['correct'])
        models[f'{q}_mlp'] = mlp_model

#         for test_train in train_x:
#             clf = models[f'{q}_catboost']
#             p = clf.predict_proba(test_train.astype('float32'))[:,1]

    print('***')

    return models

In [14]:
models = {}
best_threshold = 0.63

In [15]:
list_kol_f = {
    1:140,3:110,
    4:120, 5:220, 6:130, 7:110, 8:110, 9:100, 10:140, 11:120,
    14: 160, 15:160, 16:130, 17:140             
             }

In [16]:
df0_4 = pd.read_csv('/kaggle/input/featur/train_0_4t.csv', dtype=dtypes) 
kol_lvl = (df0_4 .groupby(['session_id'])['level'].agg('nunique') < 5)
list_session = kol_lvl[kol_lvl].index
df0_4  = df0_4 [~df0_4 ['session_id'].isin(list_session)]
df0_4 = delt_time_def(df0_4)

quests_0_4 = [1, 3] 
# list_kol_f = {1:140,3:110}

models = create_model(df0_4, quests_0_4, models, list_kol_f)
del df0_4

### quest  1 ----  train_q.shape =  (23562, 290)
### quest  3 ----  train_q.shape =  (23562, 230)
***

In [17]:
df5_12 = pd.read_csv('/kaggle/input/featur/train_5_12t.csv', dtype=dtypes)
kol_lvl = (df5_12.groupby(['session_id'])['level'].agg('nunique') < 8)
list_session = kol_lvl[kol_lvl].index
df5_12 = df5_12[~df5_12['session_id'].isin(list_session)]
df5_12 = delt_time_def(df5_12)
quests_5_12 = [4, 5, 6, 7, 8, 9, 10, 11] 

# list_kol_f = {4:110, 5:220, 6:120, 7:110, 8:110, 9:100, 10:140, 11:120}

models = create_model(df5_12, quests_5_12, models, list_kol_f)
del df5_12

### quest  4 ----  train_q.shape =  (23561, 250)
### quest  5 ----  train_q.shape =  (23561, 450)
### quest  6 ----  train_q.shape =  (23561, 270)
### quest  7 ----  train_q.shape =  (23561, 230)
### quest  8 ----  train_q.shape =  (23561, 230)
### quest  9 ----  train_q.shape =  (23561, 210)
### quest  10 ----  train_q.shape =  (23561, 290)
### quest  11 ----  train_q.shape =  (23561, 250)
***

In [18]:
df13_22 = pd.read_csv('/kaggle/input/featur/train_13_22t.csv', dtype=dtypes) 
kol_lvl = (df13_22 .groupby(['session_id'])['level'].agg('nunique') < 10)
list_session = kol_lvl[kol_lvl].index
df13_22  = df13_22 [~df13_22 ['session_id'].isin(list_session)]
df13_22 = delt_time_def(df13_22)

quests_13_22 = [14, 15, 16, 17] 
# list_kol_f = {14: 160, 15:160, 16:105, 17:140}

models = create_model(df13_22, quests_13_22, models, list_kol_f)
del df13_22

### quest  14 ----  train_q.shape =  (22986, 330)
### quest  15 ----  train_q.shape =  (22986, 330)
### quest  16 ----  train_q.shape =  (22986, 270)
### quest  17 ----  train_q.shape =  (22986, 290)
***

In [19]:
# #Saving a Model
# import joblib

# for q in quests_0_4 + quests_5_12 + quests_13_22:
#     joblib.dump(models[str(q)+"_mlp"], f'mlp_model_{q}.joblib')

In [20]:
# for q in quests_0_4 + quests_5_12 + quests_13_22:
#     models[str(q)+"_catboost"].save_model(f'cat_model_{q}.bin')

In [21]:
# for q in quests_0_4 + quests_5_12 + quests_13_22:
#     models[str(q)+"_xgboost"].save_model(f'xgb_model_{q}.bin')

In [22]:
# for q in quests_0_4 + quests_5_12 + quests_13_22:
#     models[str(q)+"_lgb"].save_model(f'lgb_model_{q}.bin')

In [23]:
#Model Reading
# import joblib
# # dir = '/kaggle/input/my-model'
# for q in quests_0_4 + quests_5_12 + quests_13_22:
#     for i in ["_catboost","_xgboost","_mlp"] :
# #             models[f'{str(q)+i}'] =  CatBoostClassifier().load_model(dir+f'cat_model_{q}.bin')

#             if i == "_catboost":
#                 models[f'{str(q)+i}'] = CatBoostClassifier().load_model(dir+f'/cat_model_{q}.bin')
#             elif i == "_xgboost":
#                 models[f'{str(q)+i}'] = XGBClassifier().load_model(dir+f'/xgb_model_{q}.bin')            
#             elif i == "_mlp" :
#                 models[f'{str(q)+i}'] = joblib.load(dir+f'/mlp_model_{q}.joblib')

**Infer Test Data**

In [24]:
import jo_wilder

try:
    jo_wilder.make_env.__called__ = False
    env.__called__ = False
    type(env)._state = type(type(env)._state).__dict__['INIT']
except:
    pass

env = jo_wilder.make_env()
iter_test = env.iter_test()

In [25]:
import time

In [26]:
g_end4 = 0
g_end5 = 0

list_q = {'0-4':quests_0_4, '5-12':quests_5_12, '13-22':quests_13_22}
for (test, sam_sub) in iter_test:
    sam_sub['question'] = [int(label.split('_')[1][1:]) for label in sam_sub['session_id']]    
    grp = test.level_group.values[0]   
    sam_sub['correct'] = 1
    sam_sub.loc[sam_sub.question.isin([5, 8, 10, 13, 15]), 'correct'] = 0  
    old_train = delt_time_def(test[test.level_group == grp])
       
    for q in list_q[grp]:
        
        start4 = time.time()
        new_train = feature_engineer(old_train, list_kol_f[q])
        new_train = feature_quest_otvet(new_train, old_train, q, list_kol_f[q])
#         new_train = feature_quest(new_train, old_train, q, kol_f)
        
        end4 = time.time() - start4
        g_end4 += end4
        
        start5 = time.time()        
        
        for i in ["_catboost","_xgboost","_mlp"] :
            clf = models[f'{str(q)+i}']
            if i == "_catboost" :
                p1 = clf.predict_proba(new_train.astype('float32'))[:,1]
            elif i == "_xgboost":
                p2 = clf.predict_proba(new_train.astype('float32').fillna(0))[:,1] 
            #elif i == "_lgbm":
            #    p3 = clf.predict_proba(new_train.astype('float32'))[:,1] 
            elif i == "_mlp" :
                p4 = clf.predict_proba(new_train.astype('float32').fillna(0))[:,1]

        p = 0.92*p1 + 0.04*p2 + 0.04*p4  # one can experiment with different weights and see if results improve

#         clf = models[f'{q}_catboost']
#         clf = models[f'{q}_xgboost']
#         p = clf.predict_proba(new_train.astype('float32'))[:,1]
#         clf = models[f'{q}_mlp']
#         p = clf.predict_proba(new_train.astype('float32').fillna(0))[:,1]
        
        end5 = time.time() - start5
        g_end5 += end5
             
        
        mask = sam_sub.question == q 
        x = int(p[0]>best_threshold)
        sam_sub.loc[mask,'correct'] = x      
        
        
    sam_sub = sam_sub[['session_id', 'correct']]      
    env.predict(sam_sub)

This version of the API is not optimized and should not be used to estimate the runtime of your code on the hidden test set.

# EDA submission.csv

In [27]:
df = pd.read_csv('submission.csv')
print( df.shape )
df.head(60)

(54, 2)

               session_id  correct
0    20090109393214576_q1        1
1    20090109393214576_q2        1
2    20090109393214576_q3        1
3    20090109393214576_q4        1
4    20090109393214576_q5        0
5    20090109393214576_q6        1
6    20090109393214576_q7        1
7    20090109393214576_q8        0
8    20090109393214576_q9        1
9   20090109393214576_q10        0
10  20090109393214576_q11        0
11  20090109393214576_q12        1
12  20090109393214576_q13        0
13  20090109393214576_q14        1
14  20090109393214576_q15        0
15  20090109393214576_q16        1
16  20090109393214576_q17        1
17  20090109393214576_q18        1
18   20090312143683264_q1        0
19   20090312143683264_q2        1
20   20090312143683264_q3        1
21   20090312143683264_q4        1
22   20090312143683264_q5        0
23   20090312143683264_q6        0
24   20090312143683264_q7        0
25   20090312143683264_q8        0
26   20090312143683264_q9        0
27  20090312143683264_q10        0
28  20090312143683264_q11        0
29  20090312143683264_q12        1
30  20090312143683264_q13        0
31  20090312143683264_q14        0
32  20090312143683264_q15        0
33  20090312143683264_q16        1
34  20090312143683264_q17        1
35  20090312143683264_q18        1
36   20090312331414616_q1        1
37   20090312331414616_q2        1
38   20090312331414616_q3        1
39   20090312331414616_q4        1
40   20090312331414616_q5        1
41   20090312331414616_q6        1
42   20090312331414616_q7        1
43   20090312331414616_q8        1
44   20090312331414616_q9        1
45  20090312331414616_q10        1
46  20090312331414616_q11        1
47  20090312331414616_q12        1
48  20090312331414616_q13        0
49  20090312331414616_q14        1
50  20090312331414616_q15        1
51  20090312331414616_q16        1
52  20090312331414616_q17        1
53  20090312331414616_q18        1